### ISSUE TITLE
Default image

### ISSUE THREAD

**Issue by empirefx** [ivantcholakov/Codeigniter-Gravatar#1]
Isn't better practice encode the URL ? as said here

https://secure.gravatar.com/site/implement/images#default-image

``` PHP
if ($default_image !== NULL)
{
      $options['d'] = urlencode($default_image);
}
```

**Comment by ivantcholakov** [comment]
Ok, what should I do?

**Comment by rsmarshall** [comment]
I have requested a transfer to you.

Good luck with it and If you leave a small credit somewhere to me that would be great. ;)

**Comment by ivantcholakov** [comment]
@rsmarshall

Would you accept if I assign to the library the MIT license? You will a license holder too.

**Comment by rsmarshall** [comment]
It's your repo now so fine by me. :)

**Comment by Ngocnguyen2016** [comment]
....
